name: twixer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  http: ^1.2.2
  loading_indicator: ^3.1.1
  crypto: any
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0



flutter:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
  uses-material-design: true
  assets:
    - assets/retweet.png
    - assets/default.jpg
